version '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network

  backend:
    build:
      context: ./back
      dockerfile: dockerfile
    ports:
      - 5000:5000
    networks:
      - app-network

networks
  app-network:
    driver: bridge