# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "docker-test" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cd ./back
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.13.0'
    - run: cd ./back
    - run: cd ./back; npm install
    - run: cd ./back; npm test
